<?php
//nodePath.php is generated by bash file findPath.sh and
//sets value for $pathToNodejs variable
include('nodejsPath.php');

// for local machine use this:
exec($pathToNodejs . ' jsonToHtml');

// for production use this:
//exec('node jsonToHtml');
?>

<?php include('include/head.php'); ?>
	<body class="home">
		<?php include('include/header.php'); ?>

		<div class="main home clearfix" role="main">
			<div class="filters">
				<span>
					<label>Teacher:</label>
					<select name="teacher-id" data-ignore="all">
						<option selected value="all">All</option>
						<?php include('generated/teachers-list.html'); ?>
					</select>
				</span>
				<span>
					<label>Class:</label>
					<select name="class-id" data-ignore="all">
						<option selected value="all">All</option>
						<?php include('generated/classes-list.html'); ?>
					</select>
				</span>
			</div>
			<ul class="list" data-filter-names="teacher-id class-id">
				<?php include('generated/sessions.html'); ?>
			</ul>
			<p class="hint">No sessions were found!</p>
		</div>

		<?php include('include/footer.php'); ?>
		<?php include('include/scripts.php'); ?>
		<script>
			var listElement = document.querySelector('div.home ul.list');
			if (listElement) {
				var filter = new FilterList({
					element: listElement,
					urlIsUpdatable: true
				});
			}
		</script>
	</body>
</html>
